version: '3.7'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_DB=trace
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes:
      - 'trace_pg_data:/bitnami/postgresql'

volumes:
  trace_pg_data: